development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: media_library_dev
  pool: 5
  username: root
  password:

test: &test
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: media_library_test
 pool: 5
 username: root
 password:
